name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the container image
        run: |
          export BUILD_DATE="$(date +%s)"
          docker build . --file Dockerfile --tag ghcr.io/ii/emacs-coder:latest
      - name: Push the container image
        run: |
          docker push ghcr.io/ii/emacs-coder:latest
